name: _Users_gadelkareem_f_projects_ai_suno.io
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - expat=2.6.4
  - libcxx=14.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.13.2
  - python_abi=3.13
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - docopt==0.6.2
      - einops==0.8.0
      - encodec==0.1.1
      - filelock==3.17.0
      - fsspec==2025.2.0
      - funcy==2.0
      - huggingface-hub==0.28.1
      - idna==3.10
      - jinja2==3.1.5
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.2
      - packaging==24.2
      - pipreqs==0.4.13
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - safetensors==0.5.2
      - scipy==1.15.1
      - sympy==1.13.1
      - tokenizers==0.21.0
      - torch==2.6.0
      - torchaudio==2.6.0
      - tqdm==4.67.1
      - transformers==4.48.2
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - yarg==0.1.10
